using System.Text;

namespace Alchemy.Docs;

internal static class PageGenerator
{
    public const string AutoGeneratedComment =
        "<!-- auto-generated by scripts/docs (dotnet run --project scripts/docs -- generate). Do not edit. -->";

    public static string Build(
        AttributeInfo attribute,
        SampleInfo? sample,
        LocaleI18n? locale,
        RepoPaths paths,
        string languageCode)
    {
        languageCode = DocLanguage.Normalize(languageCode);
        var localized = !DocLanguage.IsSource(languageCode);

        // Localized pages fall back to English XML for any missing/blank field.
        var summary = localized
            ? Fallback(locale?.Summary, attribute.Summary)
            : (attribute.Summary ?? string.Empty);

        var sb = new StringBuilder();
        sb.AppendLine(AutoGeneratedComment)
            .AppendLine()
            .Append("# ").Append(DisplayNames.ToTitle(attribute.DisplayName)).Append(" Attribute")
            .AppendLine()
            .AppendLine()
            .AppendLine(summary)
            .AppendLine();

        foreach (var note in ResolveNotes(attribute, locale, localized))
        {
            sb.Append("> [!").Append(note.Type).AppendLine("]")
                .Append("> ")
                .AppendLine(note.Body.Replace("\n", "\n> ", StringComparison.Ordinal))
                .AppendLine();
        }

        if (sample is null or { Capture: true })
        {
            foreach (var image in FindImages(paths, attribute.Slug))
            {
                sb.Append("![img](../../../images/generated/")
                    .Append(image)
                    .AppendLine(")")
                    .AppendLine();
            }
        }

        if (sample is { HasDocumentRegion: true })
        {
            var attributesDir = paths.AttributesDir(languageCode);
            var relative = Path.GetRelativePath(attributesDir, sample.FilePath)
                .Replace('\\', '/');
            sb.Append("[!code-csharp[](")
                .Append(relative)
                .Append('#')
                .Append(SampleExtractor.DocumentRegion)
                .AppendLine(")]")
                .AppendLine();
        }

        if (attribute.Parameters.Count > 0)
        {
            sb.AppendLine(DocLanguage.ParameterTableHeader(languageCode));
            sb.AppendLine("| - | - |");
            foreach (var parameter in attribute.Parameters)
            {
                var description = localized
                    ? ResolveLocalizedParam(locale, parameter)
                    : (parameter.Summary ?? string.Empty);
                sb.Append("| ")
                    .Append(parameter.Name)
                    .Append(" | ")
                    .Append(EscapeTableCell(description))
                    .AppendLine(" |");
            }

            sb.AppendLine();
        }

        return sb.ToString().TrimEnd() + "\n";
    }

    static string Fallback(string? localized, string? english) =>
        !string.IsNullOrWhiteSpace(localized)
            ? localized.Trim()
            : (english ?? string.Empty);

    static IReadOnlyList<AttributeNote> ResolveNotes(
        AttributeInfo attribute,
        LocaleI18n? locale,
        bool localized)
    {
        if (!localized)
        {
            return attribute.Notes;
        }

        if (attribute.Notes.Count == 0)
        {
            return locale?.Notes is { Count: > 0 } ? locale.Notes : [];
        }

        // Prefer localized note body per type; fall back to EN for missing/blank entries.
        var byType = (locale?.Notes ?? [])
            .Where(n => !string.IsNullOrWhiteSpace(n.Body))
            .GroupBy(n => n.Type, StringComparer.OrdinalIgnoreCase)
            .ToDictionary(g => g.Key, g => g.First(), StringComparer.OrdinalIgnoreCase);

        return attribute.Notes
            .Select(en =>
                byType.TryGetValue(en.Type, out var value)
                    ? value
                    : en)
            .ToArray();
    }

    static string ResolveLocalizedParam(LocaleI18n? locale, AttributeDocMember parameter)
    {
        if (locale?.Params is not null)
        {
            if (locale.Params.TryGetValue(parameter.Name, out var exact) &&
                !string.IsNullOrWhiteSpace(exact))
            {
                return exact.Trim();
            }

            // Tolerate PascalCase/camelCase key drift in older i18n files.
            foreach (var pair in locale.Params)
            {
                if (string.Equals(pair.Key, parameter.Name, StringComparison.OrdinalIgnoreCase) &&
                    !string.IsNullOrWhiteSpace(pair.Value))
                {
                    return pair.Value.Trim();
                }
            }
        }

        return parameter.Summary ?? string.Empty;
    }

    static string EscapeTableCell(string value) =>
        value.Replace("|", "\\|", StringComparison.Ordinal)
            .Replace("\n", " ", StringComparison.Ordinal);

    public static IReadOnlyList<string> FindImages(RepoPaths paths, string slug)
    {
        if (!Directory.Exists(paths.Images))
        {
            return [];
        }

        var prefix = "img-attribute-" + slug;
        return Directory.EnumerateFiles(paths.Images, prefix + "*.png")
            .Select(Path.GetFileName)
            .OfType<string>()
            .Order(StringComparer.Ordinal)
            .ToArray();
    }

    public static bool IsAutoGenerated(string path)
    {
        if (!File.Exists(path))
        {
            return false;
        }

        using var reader = new StreamReader(path);
        var first = reader.ReadLine();
        return first == AutoGeneratedComment;
    }
}
