namespace Alchemy.Docs;

internal static class TocUpdater
{
    public static string Update(
        string tocContent,
        IReadOnlyList<AttributeInfo> attributes,
        string languageCode)
    {
        languageCode = DocLanguage.Normalize(languageCode);
        var marker = DocLanguage.AttributeListTocMarker(languageCode);
        var lines = tocContent.Replace("\r\n", "\n", StringComparison.Ordinal).Split('\n').ToList();
        var start = lines.FindIndex(l => l.TrimEnd() == marker);
        if (start < 0)
        {
            throw new InvalidOperationException(
                $"Could not find '{marker}' in toc.yml.");
        }

        // Attributes block runs until the next top-level section that is not indented under items
        // Pattern in file: after Attributes comes blank? then "- name: Hierarchy" at same indent as "- name: Attributes"
        var end = start + 1;
        while (end < lines.Count)
        {
            var line = lines[end];
            if (line.StartsWith("- name:", StringComparison.Ordinal) &&
                !line.StartsWith("  ", StringComparison.Ordinal))
            {
                break;
            }

            end++;
        }

        var generated = BuildAttributeList(attributes, languageCode);
        var newLines = lines.Take(start).ToList();
        newLines.AddRange(generated);
        newLines.AddRange(lines.Skip(end));
        var text = string.Join("\n", newLines);
        if (!text.EndsWith('\n'))
        {
            text += "\n";
        }

        return text.Replace("\n", Environment.NewLine, StringComparison.Ordinal);
    }

    static List<string> BuildAttributeList(
        IReadOnlyList<AttributeInfo> attributes,
        string languageCode)
    {
        var marker = DocLanguage.AttributeListTocMarker(languageCode);
        var lines = new List<string>
        {
            marker,
            "  # auto-generated by scripts/docs (dotnet run --project scripts/docs -- generate). Do not edit.",
            "  items:",
        };

        string? current = null;
        foreach (var attribute in attributes)
        {
            if (!string.Equals(current, attribute.Category, StringComparison.Ordinal))
            {
                current = attribute.Category;
                lines.Add($"  - name: {attribute.Category}");
            }

            var title = DisplayNames.ToTitle(attribute.DisplayName);
            lines.Add($"  - name: {title}");
            lines.Add($"    href: attributes/{attribute.Slug}.md");
        }

        lines.Add(string.Empty);
        return lines;
    }
}
