name: CI

on:
  push:
    branches:
      - main
    paths:
      - 'Alchemy.SourceGenerator/**'
      - 'tests/Alchemy.SourceGenerator.Tests/**'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - 'Alchemy.SourceGenerator/**'
      - 'tests/Alchemy.SourceGenerator.Tests/**'
      - '.github/workflows/ci.yml'
  workflow_dispatch:

jobs:
  source-generator-tests:
    name: Source generator tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup .NET
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore Alchemy.SourceGenerator/Alchemy.SourceGenerator.sln

      - name: Build
        run: >
          dotnet build Alchemy.SourceGenerator/Alchemy.SourceGenerator.sln
          --configuration Release
          --no-restore

      - name: Test
        run: >
          dotnet run
          --project tests/Alchemy.SourceGenerator.Tests/Alchemy.SourceGenerator.Tests.csproj
          --configuration Release
          --no-build
          --
          --treenode-filter "/*/Alchemy.SourceGenerator.Tests/*/*"
